### ISSUE TITLE
grunt serve on Windows 7

### ISSUE THREAD

**Issue by srobledo** [diegonetto/generator-ionic#117]
Hi,

Everything works fine on OSX but when i try to run in on Windows 7 with GRUNT SERVE i get the following error

test\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

There is a similar issue here https://github.com/gruntjs/grunt-contrib-compass/issues/172 but no luck yet.
Any ideas? thanks!

**Comment by irangausl** [comment]
Tks Bro, It works
