### ISSUE TITLE
Grunt compress brakes cordova plugins

### ISSUE THREAD

**Issue by softBarbarian** [diegonetto/generator-ionic#139]
Hello,

When I run `grunt compress` and then `cordova build`, `cordova run ios` it seems that all the plugins are not working.
I have ionic-keyboard plugin and inappbrowser that stop working.
I was wondering if anyone had any problems with plugins+grunt compress?

Thanks

**Comment by softBarbarian** [comment]
Do I need to use ngCordova to able to use compressed and uglified code with plugins?

**Comment by jimthedev** [comment]
Hi @softBarbarian. Did you ever sort this out and if not, did you by chance look in the iOS simulator logs to see if there is any specific error code being thrown?
