### ISSUE TITLE
ionic 14 is releases.

### ISSUE THREAD

**Issue by choiks14** [diegonetto/generator-ionic#140]
please update ^^

**Comment by oligibson** [comment]
@OminStyle That worked for me, just make sure to update other ionic dependancies too

**Comment by tohagan** [comment]
I'm a newbie to Ionic but from what I understand ...

- `angular-mocks` is now merged into angular repo so can be replaced by a dependency on angular 1.3.6 for ionic v1.0.0-beta.14 .
- `angular-scenario` has been replaced by Protractor.  

... so perhaps the bower dependencies are now due for a rewrite. To fully integrate Protractor this has implication for Gruntfile as well.
