### ISSUE TITLE
deploy on ios devices or emulator in wrong path

### ISSUE THREAD

**Issue by superandrew** [diegonetto/generator-ionic#141]
Hi, I don't know if it's me but I just customized the menu example in ionic, then when I add platform and run, the application looks for the /templates folder directly in the app main folder instead of /www. Any Idea? Is it a configuration problem?

**Comment by jimthedev** [comment]
Sounds like it. Perhaps post your gruntfile and the error output?

**Comment by superandrew** [comment]
I guess it was a momentary problem, since I did nothing and everything went ok.
