### ISSUE TITLE
build fails on windows (spawn issue)

### ISSUE THREAD

**Issue by jeromerg** [diegonetto/generator-ionic#15]
Hi,
I generated a new projet just following the generation steps provided on the main page of generator-ionic. The command 'grunt serve' works fine. But the next one 'grunt build' fails with the following error:

---

...
Running "cordova:build" task

c:\Data\Kai\panini\dev\stigga-stack\client3\node_modules\grunt-contrib- compass\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
##     at Process.ChildProcess._handle.onexit (child_process.js:779:34)

what did I wrong?

Thank you in advance for your help!

Jerome

**Comment by irangausl** [comment]
Flow, Thank you very much. It worked for me.
