### ISSUE TITLE
side-menu 'side' directive not working properly.

### ISSUE THREAD

**Issue by luizrogeriocn** [diegonetto/generator-ionic#150]
I've created the default 'Side Menu' app and couldn't change the side of the menu-toggle properly.
Using side='right' will make the menu behave like it is on the right side of the screen, but the menu-toggle for the right side won't appear and the left menu-toggle will remain on the left and not working.

By using the menu-toggle='right' inside the button tag will do the trick and make the right menu button appear and actually work. BUT the left broken menu-toggle keeps appearing. I couldn't figure out how to stop it from being 'injected' into the application.

This behavior does not occur when I use ionic without this generator.

**Comment by devakone** [comment]
Have you updated your version of the ionic beta to 14 in the bower.json file?

**Comment by diegonetto** [comment]
This was an issue with an older version of Ionic.
