### ISSUE TITLE
v0.7.0: 'win-spawn' missing from package.json

### ISSUE THREAD

**Issue by tohagan** [diegonetto/generator-ionic#162]
Breaks when you run `grunt serve` .

$ grunt serve
Loading "Gruntfile.js" tasks...ERROR
 Error: Cannot find module 'win-spawn'
Warning: Task "serve" not found. Use --force to continue.

Aborted due to warnings.

- According to the [win-spawn docs](https://github.com/ForbesLindesay/win-spawn), this dependency should be safe on non-Windows platforms.

**Comment by huerlisi** [comment]
I can confirm that it is safe on Linux.

**Comment by terencenero** [comment]
Hi did anybody find a solution for this error .
I am facing it when I am Scaffolding a new ionic project

**Comment by huerlisi** [comment]
You need to add the win-spawn npm package:
```npm install win-spawn --save-dev```

**Comment by syonip** [comment]
I also have this issue.
If it cannot be added to package.json, at least maybe add a line about it to readme?
