### ISSUE TITLE
Fonts not included when using :compress

### ISSUE THREAD

**Issue by ryanseamons** [diegonetto/generator-ionic#170]
Line 277 of grunt.js needs to be changed from 

```
cwd: 'app/lib/ionic/release/fonts/',
```

to 

```
cwd: 'app/bower_components/ionic/release/fonts/',
```

So that fonts are appropriately moved when compressing.

**Comment by richardfriedman** [comment]
That worked for ionic, I use font-awesome (http://fortawesome.github.io/Font-Awesome/). 

To support any bower package with fonts I used 
```
      fonts: {
        expand: true,
        flatten: true,
        cwd: '<%= yeoman.app %>/',
        dest: '<%= yeoman.app %>/fonts/',
        src: ['**/fonts/*']
      },
```

You can also skip writing to the yeoman.app/fonts/ and write to yeoman.dist/fonts
