### ISSUE TITLE
Ionic v1.0.0-rc.1 Support

### ISSUE THREAD

**Issue by terencenero** [diegonetto/generator-ionic#181]
Hi,
Can some one add ionic v1.0.0-rc.1 support to the generator.
I tried changing the version in bower.json but faced  many errors.

**Comment by aitorllj93** [comment]
What errors have you faced? I updated recently an app to v1.0.0-rc.1 and the issues I've faced only where relative to changes in ionic directives, not generator errors

**Comment by braxtondiggs** [comment]
Try using version: 1.3.13 of Angular
