### ISSUE TITLE
Problem when i run "yo ionic"

### ISSUE THREAD

**Issue by dtrujo** [diegonetto/generator-ionic#182]
Good afternoon! When i try to run yo ionic i have this error:

Created a new Cordova project with name "Test" and id "com.example.Test"

Install plugins registered at plugins.cordova.io: grunt plugin:add:org.apache.cordova.globalization
Or install plugins direct from source: grunt plugin:add:https://github.com/apache/cordova-plugin-console.git

Installing selected Cordova plugins, please wait.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EACCES, open '/Users/diegotrujillo/.plugman/plugman.log'
    at Error (native)

Maybe i am using a new version of cordova? how can i fix it? 
thanks in advance

**Comment by aitorllj93** [comment]
It seems like a permissions error on '.plugman' folder in your home,
try:
```bash
sudo chmod 777 /Users/diegotrujillo/.plugman -R
or if it doesn't exit, create it
mkdir /Users/diegotrujillo/.plugman
sudo chmod 777 /Users/diegotrujillo/.plugman -R
```

**Comment by dtrujo** [comment]
Now its fine thank you
