### ISSUE TITLE
grunt serve "Can't Connect to the Server"

### ISSUE THREAD

**Issue by EmilioAiolfi** [diegonetto/generator-ionic#210]
'grunt serve' dont execute 'ionic serve'
I did a test with a new project with generator and did not work

If execute 'grunt ionic:serve' work.. =/

How to fix it ?

![screen shot 2015-06-14 at 21 54 04](https://cloud.githubusercontent.com/assets/999120/8151298/eb2f8f40-12df-11e5-85fe-2cfb90c9df22.png)

![screen shot 2015-06-14 at 21 50 09](https://cloud.githubusercontent.com/assets/999120/8151277/625fba0a-12df-11e5-9740-8ca5395d3691.png)

**Comment by molavec** [comment]
I have the same problem, but in my case I have two old projects that I use 'grunt serve' and work prefect. 
When I create new project I have the same problem. It's like ionic serve exist ("Done, without errors."). 
Any suggestion how to detect the bug?

**Comment by EmilioAiolfi** [comment]
@molavec, I'm trying debug the problem... I think its may be 'concurrent' task.
Specifically in this  - 'grunt.config('concurrent.ionic.tasks', ['ionic:serve', 'watch']);'

**Comment by m00g33k** [comment]
I think the problem is the port being used http://forum.ionicframework.com/t/ionic-serve-default-port/7779

Unfortunately, I've been trying to change the port and no luck.

**Comment by m00g33k** [comment]
Confirmed. Port is the problem. I tried using ionic serve --port 8080 and it worked.

**Comment by yanCode** [comment]
Having the same problem in Mac os, a workaround is to use 'grunt ionic:serve' ,  @m00g33k is correct this issue didn't exist on older versions.

**Comment by Jerome2606** [comment]
Hi,

I have the same problem on Windows 8.1.
I update the project and now 'grunt serve' stops the server as soon as it started.
'grunt serve:compress' works

**Comment by m00g33k** [comment]
Since everyone is clearly having an issue, we should file a bug report.

**Comment by EmilioAiolfi** [comment]
Guys, check line -  grunt.config('concurrent.ionic.tasks', ['ionic:serve', 'watch']);
Remove the 'watch', the ''ionic:serve'' not continue...

I think the problem is the concurrent task

![screen shot 2015-06-16 at 12 00 55](https://cloud.githubusercontent.com/assets/999120/8186246/827b2e8c-141f-11e5-9c03-1adbdd96f64d.png)

**Comment by ebosveld** [comment]
I have the same problem. Strange thing is, if I run ionic serve standalone it will run. It started happening after I updated my components...

**Comment by ebosveld** [comment]
I think I found the problem. The author of grunt-concurrent updated the package 3 days ago. This messes things up for some reason. If I go back to the previous version (```npm install grunt-concurrent@1.0.0```) the task runs without problems.

**Comment by EmilioAiolfi** [comment]
Good @ebosveld!
The problem is grunt-concurrent@1.0.1! Go back to the previous version grunt-concurrent@1.0.0 resolved.

**Comment by oori** [comment]
The issue is with grunt-concurrent "**logConcurrentOutput**".    setting it to "**false**" in the gruntfile bypasses this issue,  or downgrading to 1.0.0 as @ebosveld suggested.

**Comment by cicerohen** [comment]
@oori tank's. Helped me a lot. :D
