### ISSUE TITLE
Ionic Serve closes down inmediately after lauch 

### ISSUE THREAD

**Issue by nachojimenez** [diegonetto/generator-ionic#216]
Somehow, the concurrent:ionic task on grunt serve launches the ionic serve command, but automagically closes down afterwards.

I´ve narrowed it down to the { stdio: 'inherit' } on line 489 of the GruntFile. If i take this option out, it works, but obviously i loose all input/output capability to/from the ionic command.

I´m on io.js, BTW...

**Comment by 4word** [comment]
Having the same problem here. I can execute all the commands in the task individually fine, but its just not keeping the ionic server running when they are all together.

**Comment by nachojimenez** [comment]
grunt serve:compress does not watch for changes on templates, doesn't it?

wiredep, watch
