### ISSUE TITLE
Run on local network via a local ip

### ISSUE THREAD

**Issue by landed1** [diegonetto/generator-ionic#233]
I have had this working before and now its using localhost which doesn't work.
If an ip is set somewhere then 'grunt serve' will run on an ip address instead of localhost and this then allows a mobile to browse the resource which is very handy for testing.
I simply cant find this anymore. Thanks.

**Comment by anjum121** [comment]
You can do it like below 

` grunt serve --address 192.168.200.66 -p 9000`

where address can be your local wifi IP and port can be anything

**Comment by landed1** [comment]
Thanks - I got my understanding up to speed and now know that for the browsing your own dev machine via a device you simply must be on the same DOMAIN so you could be on a lan and have the device on wifi - so long as they are on the same domain then the device can 'find' your desktop served page....its a great time saver.
