### ISSUE TITLE
How to include grunt-angular-templates?

### ISSUE THREAD

**Issue by ThinklabsGbR** [diegonetto/generator-ionic#245]
Hey guys,

im trying to include grunt-angular-templates, but it isn't appending the destination file to the scripts.js file. Any help is appreciated.

**Comment by niyando** [comment]
@ThinklabsGbR 
Were u able to set this up?

**Comment by ThinklabsGbR** [comment]
Yeah i was able to set it up. Not quite sure which change it was, thats why i haven't mentioned anything here.

**Comment by niyando** [comment]
cool. would be great if you could list the steps or post a gist of how did u integrate grunt-angular-templates in this generator.

**Comment by ThinklabsGbR** [comment]
I've added this task to my gulp file:

```javascript
ngtemplates: {
            dist: {
                options: {
                    htmlmin: '<%= htmlmin.dist.options %>',
                    usemin: 'scripts/scripts.js'
                },
                cwd: '<%= yeoman.app %>',
                src: 'templates/{,*/}*.html',
                dest: '.temp/templateCache.js',
            }
        },
```

htmlmin.dist.options looks like this:
```javascript
htmlmin: {
            dist: {
                options: {
                    collapseWhitespace: true,
                    collapseBooleanAttributes: true,
                    removeCommentsFromCDATA: true,
                    removeOptionalTags: true
                }
            }
        },
```

And then used grunt.registerTask to register ngtemplates. However no warranty on completeness of the steps is taken over. Hope this helps you out!

**Comment by niyando** [comment]
Thanks for putting in efforts.
I have one confusion though. Why have you chosen `.temp/templateCache.js` as your dest. Shouldn't it be some file in your distribution `dist` folder?

**Comment by ThinklabsGbR** [comment]
No because i have also a minified vendor.js and scripts.js, which im concatenating in the end.

**Comment by niyando** [comment]
ah .. so
while serving locally it would use from .temp and when you build it, it would concat to concated js script.js. Right? Just to confirm, we also need to add dependency `ngtemplates`. Right?
Also, do we need to copy html templates to dist after this? since they will be served from script.js.

Apologies to bug you with so many questions :smile:

**Comment by niyando** [comment]
Tried everything you said. But it didn't append the templateCache code to script.js. Back to square 1.
