### ISSUE TITLE
install cordova in mac 10.10.5

### ISSUE THREAD

**Issue by kraom** [diegonetto/generator-ionic#264]
install cordova in mac 10.10.5  then am i getting the error !

WiNAiMs-Mac-mini:~ winaimmac$ sudo npm install -g cordova
Password:
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/winaimmac/.npm-global/bin/cordova -> /Users/winaimmac/.npm-global/lib/node_modules/cordova/bin/cordova
cordova@5.4.1 /Users/winaimmac/.npm-global/lib/node_modules/cordova
├── underscore@1.7.0
├── q@1.0.1
├── ansi@0.3.1
├── nopt@3.0.1 (abbrev@1.0.7)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, chalk@1.1.1, repeating@1.1.3, configstore@1.4.0, latest-version@1.0.1)
└── cordova-lib@5.4.1 (valid-identifier@0.0.1, opener@1.4.1, properties-parser@0.2.3, semver@4.3.6, nopt@3.0.6, shelljs@0.3.0, cordova-app-hello-world@3.10.0, npm@2.14.16, dep-graph@1.1.0, xcode@0.8.0, rc@0.5.2, npmconf@2.1.2, glob@4.0.6, aliasify@1.9.0, request@2.47.0, cordova-serve@1.0.0, init-package-json@1.9.3, tar@1.0.2, cordova-js@4.1.2)

help me thanks

**Comment by julianpoy** [comment]
This has nothing to do with this generator. Please move this to the cordova github repo.
