### ISSUE TITLE
installing splash screens and icons

### ISSUE THREAD

**Issue by aaronksaunders** [diegonetto/generator-ionic#28]
Cannot seem to find the magical place to add my personal assest such that they get added to the distribution build other than modifying the platform directories directly.

I was assuming there would be a task during the distribution that would address this.

would have jumped in myself, but I am pretty new to writing grunt scripts and don't want to mess things up

**Comment by aluna82** [comment]
Before automatically create the icon and splash
Is it possible to customize the icon and splash, so it would be different from the default? or is it possible to change the default size?
