### ISSUE TITLE
Uncaught Error: [$injector:unpr] Unknown provider: aProvider

### ISSUE THREAD

**Issue by niiamon** [diegonetto/generator-ionic#37]
When I build with grunt, everything builds properly but when I try to run the generated code, the page fails to load and all I see is a white screen. 

I noticed that there's this error in the console:

Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a <- $http <- $templateFactory <- $view <- $state

That is most likely due to minification. The weird thing is that when I generate a project and I build without any modifications to the code, everything works well but in my real project which has all my code, it breaks. 

What would be a good way to fix this?

**Comment by mautematico** [comment]
Thank you, @niiamon :+1:
