### ISSUE TITLE
add support for sass customization

### ISSUE THREAD

**Issue by morenoh149** [diegonetto/generator-ionic#38]
it'd be nice if we could choose to include the sass files from ionic so we can easily customize our apps color scheme. http://ionicframework.com/tutorials/customizing-ionic-with-sass/

**Comment by denisazevedo** [comment]
Has anyone migrated the application to use the _Ionic CLI tool_ instead of _generator-ionic_?

**Comment by jimthedev** [comment]
No. As far as I'm aware it would mean moving away from compass and the sass gem to use sass-node.

**Comment by Robinyo** [comment]
Followed @asgeo1 and @jimthedev's advice:
- http://robferguson.org/2015/07/07/customising-ionic-with-sass/

**Comment by jimthedev** [comment]
Nice @Robinyo :+1:

**Comment by siddharthshobhit** [comment]
I'hv created to scss in style folder as _login.scss and _pin.scss and imported both in main.scss. 
When i'm using the references in first page which is login.html, both scss are working properly, but  when i'm trying to use the same scss on another page, its not working, can anyone help me out.

Login Page


<ion-pane>
  <ion-header-bar class="bar title">
    <h1 class="title" align="center">Enter Mobile Number</h1>
  </ion-header-bar>
  <ion-content>
    <label class="item item-input">
      <input ng-model="ctrl.admissionNo" type="text" placeholder="User Id">
    </label><br>
    <div align="center" class="leftDiv"><a class="round-button" name='1'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">1</a></div>
    <div align="center" class="leftDiv"><a class="round-button"  name='2'   style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">2</a></div>
    <div align="center" class="rightDiv"><a class="round-button" name='3'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">3</a></div>
    <div align="center" class="leftDiv"><a class="round-button" name='4'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">4</a></div>
    <div align="center" class="leftDiv"><a class="round-button" name='5'  style="cursor: pointer;"  ng-click="ctrl.userIdClick($event)">5</a></div>
    <div align="center" class="rightDiv"><a class="round-button" name='6'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">6</a></div>
    <div align="center" class="leftDiv"><a class="round-button" name='7'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">7</a></div>
    <div align="center" class="leftDiv"><a class="round-button" name='8'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">8</a></div>
    <div align="center" class="rightDiv"><a class="round-button" name='9'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">9</a></div>
    <div align="center" class="leftDiv"><a class="custom-round-button"  style="cursor: pointer;">Forget</a></div>
    <div align="center" class="leftDiv"><a class="round-button" name='0'  style="cursor: pointer;" ng-click="ctrl.userIdClick($event)">0</a></div>
    <div align="center" class="rightDiv"><a class="custom-round-button"  style="cursor: pointer;" ng-click="ctrl.openPinView()">Next</a></div>
    <div align="center" class="leftDiv"></div>
    <div align="center" class="leftDiv"><a class="custom-round-button"  style="cursor: pointer;" ng-click="ctrl.name='' ; userId=''" >Clear</a></div>
  </ion-content>
</ion-pane>

New Page


<ion-pane>
  <ion-header-bar align-title="center"  >
    <h1 class="pintitle">Enter Mobile Number</h1>
  </ion-header-bar>
</ion-pane>


main.scss
@import "pin";
@import "login";

_pin.scss
 
.pintitle{
  background-color: #00A000
}

_login.scss
.title{
  background-color: #FF3377
}
h3{
  color: white;
  font-weight: bold;
  padding-top: 10px;
  font-size: 22px;
}
