### ISSUE TITLE
Installer does not recognise an empty directory

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [diegonetto/generator-ionic#47]
Installing ionic via yo, the installer responds:

`Installing selected Cordova plugins, please wait.
✗ Please run `yo ionicjs` in an empty directory, or in that of an already existing cordova project.`

A screencap of the issue:

![untitled](https://cloud.githubusercontent.com/assets/2670100/2832612/72c499ae-cfc6-11e3-85ca-19daba1892e7.gif)

**Comment by msingaraju** [comment]
I did 
A) Remove the app folder(s) 
B) Did run npm intall -g cordova
C) Create the app folder and cd to app folder
D) yo ionic

This resolved the problem for me

**Comment by julianbei** [comment]
you have to create the app folder before adding it to you IDE. This is how it works for me...

**Comment by devotis** [comment]
Another reason for a non empty directory is when you decided to `git init` after creating the directory and before `yo ionic`. The directory will contain a (hidden) .git file and the non empty directory error will occur.

**Comment by julianbei** [comment]
this should really be fixed it is very annoying

**Comment by alanquigley** [comment]
This issue is happening on version 0.7.3?

**Comment by nishantparashar52** [comment]
This Helped me out.http://cordova.apache.org/docs/en/5.0.0//guide_cli_index.md.html#The%20Command-Line%20Interface

**Comment by ingadi** [comment]
I still have this problem even after updating.

**Comment by ingadi** [comment]
It seems that when any cordova plugins are included the error happens, when you exclude them the process completes fine

**Comment by molerat619** [comment]
I still have that problem and only @axelingadi 's "fix" worked for me, but that's not the way it's meant to be
