### ISSUE TITLE
grunt emulate:android loads a blank page

### ISSUE THREAD

**Issue by bmwertman** [diegonetto/generator-ionic#67]
When I would run grunt emulate:android on it's own when the emulator launches it never really loads. It just shows this:
![screen shot 2014-07-03 at 8 13 08 pm](https://cloud.githubusercontent.com/assets/2573903/3477097/13363bb4-0310-11e4-9312-c6bb24e98161.png)

But if I first start my emulator from the command line with this command

emulator -avd AVD_for_nexus_5_by_Google -gpu on

The emulator starts up almost immediately.

I then run the same grunt emulate:android command and it loads my app in the emulator. But always as just a blank white page. Even though grunt serve shows my page content in the browser without any trouble.

**Comment by lotsabackscatter** [comment]
Awesome! Cheers @jimthedev.

Just wanted to point out that it turns out, even having `<base href="/">` in index.html is enough to break it.

**Comment by JerTClark** [comment]
Another Thank you! @jimthedev ! You rock!
HTML5 mode was the culprit in my case as well
