### ISSUE TITLE
Scaffold common Cordova hooks

### ISSUE THREAD

**Issue by diegonetto** [diegonetto/generator-ionic#72]
Following the best practices described here - http://devgirl.org/2013/11/12/three-hooks-your-cordovaphonegap-project-needs/

**Comment by pcantrell** [comment]
In case anybody wanders into this stale-but-still-high-pagerank thread, the current state of the … er … art appears to be this: https://www.raymondcamden.com/2015/04/20/ionic-adds-a-new-state-feature/

In brief:
1. Install your plugin using `cordova plugin add` (which will put it in `plugins/`, which is probably gitignored).
2. When things looks good, run `ionic state save`.
3. Have other devs run `ionic state restore` when checking out the project.
