### ISSUE TITLE
Error after platform:add:android

### ISSUE THREAD

**Issue by cschaf** [diegonetto/generator-ionic#92]
Hello community,
i have a strange problem while adding android as platform. After my project has been created, I run grunt test. Then grunt platform:add:android. Now i get the following Lines: Is this my mistake?

---

d:\WebProjects\CvsBirthdayManager>grunt platform:add:android
Running "platform:add:android" (platform) task
Creating android project...

Creating Cordova project for the Android platform:

```
    Path: platforms\android

    Package: com.example.CvsBirthdayManager

    Name: CvsBirthdayManager

    Android target: android-19
```

Copying template files...

Running: android update project --subprojects --path "platforms\android" --targe
t android-19 --library "CordovaLib"

Resolved location of library project to: D:\WebProjects\CvsBirthdayManager\platf
orms\android\CordovaLib
Updated and renamed default.properties to project.properties
Updated local.properties
No project name specified, using Activity name 'CvsBirthdayManager'.
If you wish to change it, edit the first line of build.xml.
Added file D:\WebProjects\CvsBirthdayManager\platforms\android\build.xml
Added file D:\WebProjects\CvsBirthdayManager\platforms\android\proguard-project.
txt
Updated project.properties
Updated local.properties
No project name specified, using project folder name 'CordovaLib'.
If you wish to change it, edit the first line of build.xml.
Added file D:\WebProjects\CvsBirthdayManager\platforms\android\CordovaLib\build.
xml
Added file D:\WebProjects\CvsBirthdayManager\platforms\android\CordovaLib\progua
rd-project.txt

Project successfully created.

> > path.js:116
> >         throw new TypeError('Arguments to path.resolve must be strings');
> > ^
> > TypeError: Arguments to path.resolve must be strings
> >     at Object.exports.resolve (path.js:116:15)
> >     at d:\WebProjects\CvsBirthdayManager\hooks\after_prepare\icons_and_splash
> > screens.js:60:27
> >     at Function.forEach (d:\WebProjects\CvsBirthdayManager\node_modules\lodas
> > h\dist\lodash.js:3297:15)
> >     at d:\WebProjects\CvsBirthdayManager\hooks\after_prepare\icons_and_splash
> > screens.js:56:7
> >     at f (d:\WebProjects\CvsBirthdayManager\node_modules\glob\node_modules\on
> > ce\once.js:16:25)
> >     at Glob.<anonymous> (d:\WebProjects\CvsBirthdayManager\node_modules\glob\
> > glob.js:100:7)
> >     at Glob.emit (events.js:95:17)
> >     at Glob.next (d:\WebProjects\CvsBirthdayManager\node_modules\glob\glob.js
> > :357:10)
> >     at Glob._processEmitQueue (d:\WebProjects\CvsBirthdayManager\node_modules
> > \glob\glob.js:322:12)
> >     at Glob.emitMatch (d:\WebProjects\CvsBirthdayManager\node_modules\glob\gl
> > ob.js:302:8)
> > Hook failed with error code 8: d:\WebProjects\CvsBirthdayManager\hooks\after_
> > prepare\icons_and_splashscreens.js
> > Warning: Task "platform:add:android" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2014-08-25 10:32:09 UTC)
platform:add:android  2.1s  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
Total 2.1s

---

**Comment by Gijobs** [comment]
Had the same problem, try the fix of Diegonetto, but I have the same error..

(When I do : cordova build wp8)

**Comment by benbristow** [comment]
```
Running command: "C:\Program Files\nodejs\node.exe" C:\Users\Ben\Projects\myawesomeapp-app\hooks\after_prepare\020_rem
ove_sass_from_platforms.js C:\Users\Ben\Projects\myawesomeapp-app

Running command: "C:\Program Files\nodejs\node.exe" C:\Users\Ben\Projects\myawesomeapp-app\hooks\after_prepare\icons_a
nd_splashscreens.js C:\Users\Ben\Projects\myawesomeapp-app

>> path.js:111
>>       throw new TypeError('Arguments to path.resolve must be strings');
>>             ^
>> TypeError: Arguments to path.resolve must be strings
>>     at Object.win32.resolve (path.js:111:13)
>>     at C:\Users\Ben\Projects\myawesomeapp-app\hooks\after_prepare\icons_and_splashscreens.js:54:19
>>     at arrayEach (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\lodash\index.js:1289:13)
>>     at Function.forEach (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\lodash\index.js:5710:11)
>>     at Object.<anonymous> (C:\Users\Ben\Projects\myawesomeapp-app\hooks\after_prepare\icons_and_splashscreens.js:53
:3)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Function.Module.runMain (module.js:501:10)
>> Error: Hook failed with error code 1: C:\Users\Ben\Projects\myawesomeapp-app\hooks\after_prepare\icons_and_splashsc
reens.js
>>     at C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.j
s:194:23
>>     at _rejected (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\q.js:797:24)
>>     at C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\q.js:823:30
>>     at Promise.when (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\q.js:1035:31)
>>     at Promise.promise.promiseDispatch (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\
q.js:741:41)
>>     at C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\q.js:557:44
>>     at flush (C:\Users\Ben\Projects\myawesomeapp-app\node_modules\cordova\node_modules\q\q.js:108:17)
>>     at process._tickCallback (node.js:355:11)
Warning: Task "platform:add:browser" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-02-25 21:14:09 UTC)
platform:add:browser  3.5s  ████████████████████████████████████████████████████████████████████████████████ 100%
Total 3.5s


C:\Users\Ben\Projects\myawesomeapp-app>
```

Having this issue for all platforms I've tried (WP8/Windows8/Browser) on Windows 10. (I'm guessing it's the same for WP8). Using the icons_and_splashscreens.js from this repo. Even did a whole re-creation from yo with the latest package of the generator, still the same problem.

Any info on this issue would be great.

**Comment by Gijobs** [comment]
I'm not alone so.. I didn't fond anyrhing new on this issues ;(

**Comment by kuzman** [comment]
I had this problem on windows. The issue was caused because I had some other directories except the 'android' directory under 'platforms'... Hope this helps!

**Comment by Gijobs** [comment]
Thanks you Kuzman ! I have the same trouble !


*HOTTON Joris* - Découvrez mon CV en ligne
<http://www.doyoubuzz.com/joris-hotton>

2015-04-19 23:10 GMT+02:00 kuzman <notifications@github.com>:
